# Generated by Django 4.2.26 on 2026-01-17 01:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Khách hàng (Client)'), ('CTV', 'Cộng tác viên')], default='CLIENT', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='Link cần review (Google Maps, Facebook, Shopee...)')),
                ('content_instruction', models.TextField(help_text='Hướng dẫn nội dung review cho CTV')),
                ('price_per_review', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_target', models.IntegerField(default=10)),
                ('quantity_done', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Đang chạy'), ('PAUSED', 'Tạm dừng'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='RUNNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertifyAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email xác nhận')),
                ('login_username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Tên tài khoản')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mật khẩu (Hashed)')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'db_table': 'convertify_auth',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung review đã viết')),
                ('proof_image', models.ImageField(blank=True, help_text='Ảnh bằng chứng', null=True, upload_to='proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('reject_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.campaign')),
                ('ctv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campaign', 'ctv')},
            },
        ),
    ]
